config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'static_pages#home'

  resources :users, only: %i[show], param: :uuid
  resource :user_profile, only: %i[show edit update]
  get 'update_user_profile', to: 'user_profiles#update'
  resources :boards, only: %i[create], param: :uuid
  get 'message', to: 'boards#index', as: 'message'
  resources :chatrooms, only: %i[index show], param: :uuid

  resources :todos, only: %i[index]

  namespace :api do
    namespace :v1 do
      resources :current_user, only: %i[index]
      resources :users, only: %i[index show], param: :uuid
      resources :posts, only: %i[index create update destroy], param: :uuid
      resources :boards, only: %i[index], param: :uuid
      resources :messages, only: %i[index create update destroy], param: :uuid
    end
  end
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
	before_action :set_user, only: %i[show edit update]

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_profile_path, notice: t('.success')
    else
      flash.now[:danger] = 'error!'
      render 'edit'
    end
  end

  private

  def set_user
  	@user = current_user
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :image)
  end
end

app/views/user_profiles/edit.html.erb
<h1>プロフィール編集</h1>
<%= form_with(model: @user, url: user_profile_path, local: true, html: { method: :patch, class: '' }) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.text_field :last_name %>
  <%= f.file_field :image %>
  <%= f.submit '更新', class: 'primary-btn' %>
<% end %>

app/views/user_profiles/show.html.erb
<h1><%= @user.full_name %></h1>
<p><%= @user.name %></p>
<%= image_tag(@user.image.url.to_s) if @user.image.present? %>
<%= link_to 'プロフィール編集', edit_user_profile_path %>